### ISSUE TITLE
Still being supported?

### ISSUE THREAD

**Issue by dfkettle** [stevenrobertson/cuburn#12]
Is cuburn still being supported by anyone? I don't see any issues posted in almost 3 years. I was wondering if there are plans to migrate it to Python 3 (it looks like it was written for Python 2, although no mention is made in the requirements).

Thanks.

**Comment by dfkettle** [comment]
Judging by the overwhelming response, I guess not.

**Comment by davity** [comment]
Haven't seen much movement in a long time.
If you're interested, Fractorium has absorbed the ideas of this project along with other ones and merged them all together. The result is pretty impressive and it's very well documented too.

http://fractorium.com
https://bitbucket.org/mfeemster/fractorium

**Comment by dfkettle** [comment]
> Haven't seen much movement in a long time.
> If you're interested, Fractorium has absorbed the ideas of this project along with other ones and merged them all together. The result is pretty impressive and it's very well documented too.
> 
> http://fractorium.com
> https://bitbucket.org/mfeemster/fractorium

Thanks, I'll check it out.
